version: "3.9"

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3010:3010"    
    volumes:
      - ./api:/app
      - /app/node_modules
    command: sh -c "npx prisma migrate deploy && npm run dev"
    depends_on:
      - postgres  

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0
  postgres:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: open_innovation
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
